repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3.10
      name: black
      entry: black
      args: [--config, pyproject.toml]
      files: \.(py|pyi)$