name: Django Unit Tests + CI/CD e2e Workflow

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      - '*/*'
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit Tests with pytest framework and generate coverage report
      working-directory: ./access_amherst_backend
      run: pytest --cov=access_amherst_algo --cov-config=.coveragerc --cov-fail-under=85
    - name: Run Django Compilation CI/CD Tests
      run: |
        python ./access_amherst_backend/manage.py test
    - name: Black Code Formatter Command Run
      run: |
        python -m black ./
