name: Pytest + CI/CD 

on:
  schedule:
    - cron: "*/7 * * * *"
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
      - '*/*'
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Unit Tests with pytest framework and generate coverage report
      working-directory: ./access_amherst_backend
      run: |
        pytest --cov=access_amherst_algo --cov-config=.coveragerc --cov-fail-under=90
    - name: Coveralls Workflow
      working-directory: ./access_amherst_backend
      run: |
        coveralls --service=github
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Django Compilation CI/CD Tests
      run: |
        python ./access_amherst_backend/manage.py test
    - name: Black Code Formatter Command Run
      run: |
        python -m black ./

  workflow:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Daily Mammoth Workflow, Hub Workflow, and Remove Old Events
      working-directory: ./access_amherst_backend
      run: |
        python manage.py daily_mammoth_workflow
        python manage.py hub_workflow
        python manage.py remove_old_events
    - name: Commit and Push to githubworkflows/cron-job
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated workflow and cleanup commit"
        git push origin githubworkflows/cron-job
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
